//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        public Campaign()
        {
            this.CampaignEmails = new HashSet<CampaignEmail>();
            this.JobPosts = new HashSet<JobPost>();
        }
    
        public System.Guid CampaignId { get; set; }
        public string DefaultJobPostId { get; set; }
        public string InternalName { get; set; }
        public string PublicName { get; set; }
        public string HostUrl { get; set; }
        public CampaignType CampaignType { get; set; }
        public Status Status { get; set; }
        public bool IsPublic { get; set; }
        public string RequireSSL { get; set; }
        public string HasClientEULA { get; set; }
        public string ClientEULAText { get; set; }
        public Nullable<System.DateTimeOffset> StartDate { get; set; }
        public Nullable<System.DateTimeOffset> EndDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Recruitment Recruitment { get; set; }
        public virtual ICollection<CampaignEmail> CampaignEmails { get; set; }
        public virtual ICollection<JobPost> JobPosts { get; set; }
    }
}
