//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignEmail
    {
        public System.Guid CampaignEmailId { get; set; }
        public System.Guid CampaignId { get; set; }
        public System.Guid EmailTemplateId { get; set; }
        public Nullable<System.Guid> LogoImageId { get; set; }
        public bool IsRequired { get; set; }
        public JobEmailType EmailType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
    }
}
