//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    
    public enum CampaignRepStatus : int
    {
        NotQualified = 0,
        Qualified = 1,
        Applied = 2,
        Interviewing = 3,
        Rejected = 4,
        Offered = 5,
        Admitted = 6,
        AwaitingResponse = 7,
        Other = 8
    }
}
