//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignQuestion
    {
        public CampaignQuestion()
        {
            this.CampaignQuestionChoices = new HashSet<CampaignQuestionChoice>();
        }
    
        public System.Guid CampaignQuestionId { get; set; }
        public System.Guid CampaignId { get; set; }
        public string Text { get; set; }
        public CampaignQuestionType Type { get; set; }
        public bool IsRequired { get; set; }
        public Nullable<bool> IsSingleLine { get; set; }
        public Nullable<int> EntryFieldNumber { get; set; }
        public Nullable<CampaignQuestionValidationType> ValidationType { get; set; }
        public string Status { get; set; }
        public int Order { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<CampaignQuestionChoice> CampaignQuestionChoices { get; set; }
    }
}
