//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignQuestionChoice
    {
        public System.Guid CampaignQuestionChoiceId { get; set; }
        public System.Guid CampaignQuestionId { get; set; }
        public string Text { get; set; }
        public int Score { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
