//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    
    public enum CampaignQuestionValidationType : int
    {
        Date = 1,
        Email = 2,
        ZipCode = 3,
        Number = 0
    }
}
