//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    
    public enum EducationLastCompleted : int
    {
        Unknown = 0,
        ElementarySchool = 1,
        MiddleSchool = 2,
        HighSchool = 3,
        SomeCollege = 4,
        TwoYearCollege = 5,
        FourYearCollege = 6,
        Masters = 7,
        Doctorate = 8
    }
}
