//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    
    public enum JobEmailType : int
    {
        CampaignBlast = 0,
        Interview = 1,
        Offer = 2,
        Welcome = 3,
        Rejection = 4
    }
}
