//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPost
    {
        public System.Guid JobPostId { get; set; }
        public System.Guid CampaignId { get; set; }
        public string Code { get; set; }
        public string Headline { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public string PromotionalLink { get; set; }
        public System.Guid LogoImageId { get; set; }
        public Status Status { get; set; }
        public bool IsFeatured { get; set; }
        public System.DateTime Deadline { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
