//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitmentDocumentConfig
    {
        public System.Guid RecruitmentDocumentConfigId { get; set; }
        public System.Guid RecruitmentId { get; set; }
        public RecruitmentDocumentType RecruitmentDocumentType { get; set; }
        public string Title { get; set; }
        public string AdditionalMessage { get; set; }
        public string AdditionalTerms { get; set; }
        public bool RequireW2 { get; set; }
    }
}
