//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recruitment
    {
        public Recruitment()
        {
            this.RecruitmentAgeGroupPreferences = new HashSet<RecruitmentAgeGroupPreference>();
            this.RecruitmentBusinessPreferences = new HashSet<RecruitmentBusinessPreference>();
            this.RecruitmentDocumentConfigs = new HashSet<RecruitmentDocumentConfig>();
        }
    
        public System.Guid RecruitmentId { get; set; }
        public string PortalId { get; set; }
        public RecruitmentType Type { get; set; }
        public int RepGoal { get; set; }
        public int CampusGoal { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Gender { get; set; }
        public MaritalStatusType MaritalStatus { get; set; }
        public int MinAge { get; set; }
        public int MaxAge { get; set; }
        public int MinChildren { get; set; }
        public RecruitmentLocationPreferenceType LocationPreferenceType { get; set; }
        public string City { get; set; }
        public System.Guid StateId { get; set; }
        public bool ExcludeLowRatedRep { get; set; }
        public bool RequireExperiencedRep { get; set; }
        public string RegionRadius { get; set; }
        public string RegionZip { get; set; }
        public int MinFacebookFriends { get; set; }
        public int MaxFacebookFriends { get; set; }
        public int MinTwitterFollowers { get; set; }
        public int MaxTwitterFollowers { get; set; }
    
        public virtual ICollection<RecruitmentAgeGroupPreference> RecruitmentAgeGroupPreferences { get; set; }
        public virtual ICollection<RecruitmentBusinessPreference> RecruitmentBusinessPreferences { get; set; }
        public virtual ICollection<RecruitmentDocumentConfig> RecruitmentDocumentConfigs { get; set; }
    }
}
