//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rep
    {
        public Rep()
        {
            this.RepAddresses = new HashSet<RepAddress>();
            this.RepBusinesses = new HashSet<RepOrganization>();
        }
    
        public System.Guid RepId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public System.Guid StateId { get; set; }
        public string CountryId { get; set; }
        public string Zip { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsMale { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string ResumeFileId { get; set; }
        public AgeGroupType AgeGroupType { get; set; }
        public bool IsGlobal { get; set; }
        public Status Status { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime DateModified { get; set; }
        public string ModifiedBy { get; set; }
        public string Website { get; set; }
        public string PhotoId { get; set; }
        public string EducationLastCompleted { get; set; }
        public MaritalStatusType MaritalStatus { get; set; }
        public bool LiveOnOrOffCampus { get; set; }
    
        public virtual ICollection<RepAddress> RepAddresses { get; set; }
        public virtual ICollection<RepOrganization> RepBusinesses { get; set; }
        public virtual Rep_Calc RepBusiness_calc { get; set; }
        public virtual File File { get; set; }
    }
}
