//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepNationContainer : DbContext
    {
        public RepNationContainer()
            : base("name=RepNationContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Campaign> Campaigns { get; set; }
        public DbSet<Rep> Reps { get; set; }
        public DbSet<Business> Businesses { get; set; }
        public DbSet<CampaignRep> CampaignReps { get; set; }
        public DbSet<JobPost> JobPosts { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<RecruitmentBusinessPreference> RecruitmentBusinessPreferences { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<CampaignEmail> CampaignEmails { get; set; }
        public DbSet<CampaignQuestion> CampaignQuestions { get; set; }
        public DbSet<CampaignQuestionChoice> CampaignQuestionChoices { get; set; }
        public DbSet<RepCampaignQuestionChoice> RepCampaignQuestionChoices { get; set; }
        public DbSet<RecruitmentDocumentConfig> RecruitmentDocumentConfigs { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<RepAddress> RepAddresses { get; set; }
        public DbSet<Recruitment> Recruitments { get; set; }
        public DbSet<RecruitmentAgeGroupPreference> RecruitmentAgeGroupPreferences { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<Rep_Calc> Rep_Calc { get; set; }
        public DbSet<RepOrganization> RepOrganizations { get; set; }
        public DbSet<RepScreeningScoreCalculated> RepScreeningScoreCalculateds { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<HighSchool> HighSchools { get; set; }
        public DbSet<College> Colleges { get; set; }
        public DbSet<Company> Companies { get; set; }
    }
}
