//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepNationRevive.DBDesign
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepOrganization
    {
        public System.Guid RepOrganizationId { get; set; }
        public System.Guid RepId { get; set; }
        public System.Guid BusinessId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string HighSchoolId { get; set; }
        public string CollegeId { get; set; }
        public string CompanyId { get; set; }
        public string HighSchoolGraduationSeason { get; set; }
        public string HighSchoolGraduationYear { get; set; }
        public string CollegeGraduationSeason { get; set; }
        public string CollegeGraduationYear { get; set; }
        public string MonthlyIncome { get; set; }
        public string NoOfChildren { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
